batch_size: 32
batch_group_size: 8
sample_size: 1
queue_size: 32  # number of batches stored in queue
min_dequeue_ratio: 0.33
adam:
  beta1: 0.9
  beta2: 0.999
initial_learning_rate: 0.002
learning_rate_decay_halflife: 100000
decay_learning_rate: True
use_cmudict: False  # Use CMUDict during training to learn pronunciation of ARPAbet phonemes